spring.application.name=SHS App Launch Service
server.port=8080
server.servlet.context-path=/applaunch

# --- Datasource (point to the same DB as portal) ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.url=${aws-db-url}
spring.datasource.username=${aws-db-username}
spring.datasource.password=${aws-db-password}
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.main.allow-circular-references=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.continue-on-error=true
spring.main.web-application-type=servlet

spring.config.import=optional:aws-secretsmanager:shs-portal-dev

spring.flyway.enabled=false

# JWT Builder Configurations-->
jwt.secret=${enc-secret}

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus
#management.endpoints.web.exposure.include=* --to restrict in higher environment
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.metrics.export.prometheus.enabled=true

# To monitor DB connection pool
management.metrics.enable.jvm=true
management.metrics.enable.hikaricp=true

shs.portal.url=https://shsdev.symphonyhealth.com/symphonyweb/service

#MSTR cloud login endpoints
mstr.api.loginPath=/MicroStrategyLibrary/api/auth/login
mstr.api.logoutPath=/MicroStrategyLibrary/api/auth/logout
#mstr login mode: 1=Standard, 16=LDAP
mstr.login.mode=1
mstr.form.actionUrl=/MicroStrategy/servlet/mstrWeb
mstr.identity.tokenPath=/MicroStrategyLibrary/api/auth/identityToken
mstr.delegatePath=/MicroStrategyLibrary/api/auth/delegate
mstr.landing.page=MicroStrategyLibrary/app
mstr.user.password=${mstr-user-password}

# QlikSense SenseDev -->
sense.symphonyhealthcloud.com_xrfkey=${qlik-sense-xrfkey}
sense.symphonyhealthcloud.com_host=sense.symphonyhealthcloud.com
sense.symphonyhealthcloud.com_virtualProxy=ticket
sense.symphonyhealthcloud.com_proxyCertPass=${qlik-sense-proxy-cert-pass}
sense.symphonyhealthcloud.com_rootCertPass=${qlik-sense-root-cert-pass}
sense.symphonyhealthcloud.com_userDirectory=CLIENT
sense.symphonyhealthcloud.com_folderPath=qlikClientCertificate
sense.symphonyhealthcloud.com_clientCertificateFile=client_prod
sense.symphonyhealthcloud.com_rootCertificateFile=root_prod

# QlikSense SenseTest -->
sensetest.symphonyhealthcloud.com_xrfkey=${qlik-sense-xrfkey}
sensetest.symphonyhealthcloud.com_host=sensetest.symphonyhealthcloud.com
sensetest.symphonyhealthcloud.com_virtualProxy=ticket
sensetest.symphonyhealthcloud.com_proxyCertPass=${qlik-sense-proxy-cert-pass}
sensetest.symphonyhealthcloud.com_rootCertPass=${qlik-sense-root-cert-pass}
sensetest.symphonyhealthcloud.com_userDirectory=CLIENT
sensetest.symphonyhealthcloud.com_folderPath=qlikClientCertificate
sensetest.symphonyhealthcloud.com_clientCertificateFile=client_test_paral
sensetest.symphonyhealthcloud.com_rootCertificateFile=root_test_paral

# QlikSense SenseProd -->
senseprod.symphonyhealthcloud.com_xrfkey=${qlik-sense-xrfkey}
senseprod.symphonyhealthcloud.com_host=senseprod.symphonyhealthcloud.com
senseprod.symphonyhealthcloud.com_virtualProxy=ticket
senseprod.symphonyhealthcloud.com_proxyCertPass=${qlik-sense-proxy-cert-pass}
senseprod.symphonyhealthcloud.com_rootCertPass=${qlik-sense-root-cert-pass}
senseprod.symphonyhealthcloud.com_userDirectory=CLIENT
senseprod.symphonyhealthcloud.com_folderPath=qlikClientCertificate
senseprod.symphonyhealthcloud.com_clientCertificateFile=client_prod_paral
senseprod.symphonyhealthcloud.com_rootCertificateFile=root_prod_paral

#QlikViewCredentials Configurations -->
groups=
qkclusterprd.symphonyhealth.com_qlikViewServerURL=https://qkclusterprdsso.symphonyhealth.com/QVAJAXZFC/getwebticket.aspx
qkclusterprd.symphonyhealth.com_QVAdministrator=${qlik-username}
qkclusterprd.symphonyhealth.com_QVAdministratorPassword=${qlik-password}
qkclusterprd.symphonyhealth.com_domainName=https://qkclusterprdsso.symphonyhealth.com
qkclusterprd.symphonyhealth.com_domain=Client
qkclusterprd.symphonyhealth.com_protocol=https
qkclusterprd.symphonyhealth.com_url=qkclusterprdsso.symphonyhealth.com
qkclusterprd.symphonyhealth.com_port=443

groups=
vantage.symphonyhealth.com_qlikViewServerURL=https://vantage.symphonyhealthcloud.com/QVAJAXZFC/getwebticket.aspx
vantage.symphonyhealth.com_QVAdministrator=${qlik-username}
vantage.symphonyhealth.com_QVAdministratorPassword=${qlik-password}
vantage.symphonyhealth.com_domainName=https://vantage.symphonyhealthcloud.com
vantage.symphonyhealth.com_domain=Client
vantage.symphonyhealth.com_protocol=https
vantage.symphonyhealth.com_url=vantage.symphonyhealthcloud.com
vantage.symphonyhealth.com_port=443

# Logging Service URL
logging.service.url=http://localhost:8080/portallogs/service/logging

serverurl=https://shsdev.symphonyhealth.com/
server.forward-headers-strategy=framework